[package]
name = "ruci"
version = "0.0.8"
edition = "2021"
readme = "README.md"
description = "a network proxy framework"
categories = ["network-programming"]
license = "MIT OR Apache-2.0"

[profile.release]
lto = "fat"
codegen-units = 1
debug = false
strip = true
debug-assertions = false
incremental = false
#opt-level = 'z' # use this and upx will get the smallest binary # default is 3


[workspace]
members = [
  "rucimp",
  "./",
  "crates/macro_map",
  "crates/ruci-cmd",
  "crates/ruci-rustls22",
  "crates/ruci-rustls21",
  "crates/ruci-recorder",
]

[workspace.dependencies]
tracing = "0.1"
rand = { version = "0.9" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
bytes = "1"
user_trait = "0.1.1"
futures = "0.3"
futures-lite = "2"
futures-util = "0.3"
async-trait = "0.1"
pin-project-lite = "0.2"
pin-project = "1.1"
scopeguard = "1.2"
parking_lot = "0.12"
smallvec = { version = "1.13", features = ["serde"] }
dyn-clone = "1"
tar = "0.4"
axum = { version = "0.8", features = ["ws"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }

data-source = { version = "0.1.5", features = ["file_server"] }
utoipa = { version = "5", features = ["axum_extras"] }

reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "stream",
  "rustls-tls",
] }

toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"


[dependencies]
macro_map = { path = "crates/macro_map" }
tracing = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
user_trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
async-trait = { workspace = true }
tokio-util = { workspace = true }
pin-project-lite = { workspace = true }
scopeguard = { workspace = true }
parking_lot = { workspace = true }
smallvec = { workspace = true }
dyn-clone = { workspace = true }


typetag = "0.2"
typed-builder = "0.20"
bitflags = "2"
url = "2"              #for http proxy
base64 = "0.22"
sha2 = "0.10"          #for trojan


hickory-resolver = { version = "0.24", features = ["serde-config"] }


tun = { version = "0.7", features = ["async"] }

[features]


trace = []


[dev-dependencies]
lazy_static = "1"

env_logger = "0.11"
criterion = { version = "0.5", features = ["async_tokio"] }

[[bench]]
name = "mathadd"
harness = false
