workspace = { members = [
    "rucimp",
    "./",
    "crates/macro_map",
    "crates/ruci-cmd",
    "crates/ruci-tls",
] }
[package]
name = "ruci"
version = "0.0.8"
edition = "2021"
readme = "README.md"
description = "a network proxy framework"
categories = ["network-programming"]

[profile.release]
lto = "fat"
codegen-units = 1
debug = false
strip = true
debug-assertions = false
incremental = false
#opt-level = 'z' # use this and upx will get the smallest binary

[dependencies]
macro_map = { path = "crates/macro_map" }

tracing = "0.1"
rand = { version = "0.8", features = ["small_rng"] }
bytes = "1"
futures = "0.3"
futures-util = "0.3"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
pin-project-lite = "0.2"
scopeguard = "1.2"
parking_lot = "0.12"
smallvec = { version = "1.13", features = ["serde"] }

serde = { version = "1", features = ["derive"] }

typetag = "0.2"
dyn-clone = "1"
anyhow = "1"
typed-builder = "0.18"
bitflags = "2"
url = "2"              #for http proxy
base64 = "0.21"
sha2 = "0.10"          #for trojan


hickory-resolver = { version = "0.24", features = ["serde-config"] }


tun = { version = "0.7", features = ["async"], optional = true }

[features]


trace = []


[dev-dependencies]
lazy_static = "1"

env_logger = "0.11"
criterion = { version = "0.5", features = ["async_tokio"] }

[[bench]]
name = "mathadd"
harness = false
