use std::{fs, vec};

use tracing::debug;

/*
从 下面网页学 /etc/resolv.conf
https://www.baeldung.com/linux/etc-resolv-conf-file

一般内容大概是

# Generated by NetworkManager
nameserver 192.168.1.1

但也可以有 search, sortlist, options,

*/

const LINUX_DNS_FILE: &str = "/etc/resolv.conf";

pub fn get_sys_dns() -> Vec<String> {
    #[cfg(target_os = "linux")]
    {
        let r = fs::read_to_string(LINUX_DNS_FILE);
        match r {
            Ok(s) => {
                return s
                    .split('\n')
                    .filter(|x| x.starts_with("nameserver"))
                    .map(|x| x.split(' ').last().unwrap_or_default().to_string())
                    .collect()
            }
            Err(_) => {}
        }
    }

    return vec![];
}

pub fn set_sys_dns(list: Vec<&str>) -> std::io::Result<()> {
    #[cfg(target_os = "linux")]
    {
        debug!("setting system dns");
        let mut s = String::from("# Generated by ruci\n");
        list.iter().for_each(|x| {
            s.push_str("nameserver ");
            s.push_str(x);
            s.push('\n')
        });

        fs::write(LINUX_DNS_FILE, s.as_bytes())?;
    }

    Ok(())
}

#[test]
fn test_get() {
    let r = get_sys_dns();
    println!("{r:?}")
}

#[test]
fn test_set() {
    let r = get_sys_dns();
    let r = set_sys_dns(r.iter().map(|x| x.as_str()).collect());
    println!("{r:?}");

    let r = get_sys_dns();

    println!("{r:?}")
}
