/*!
Provides functions to set or get system dns servers.
 */
use std::vec;

/*
从 下面网页学 /etc/resolv.conf
https://www.baeldung.com/linux/etc-resolv-conf-file

一般内容大概是

# Generated by NetworkManager
nameserver 192.168.1.1

但也可以有 search, sortlist, options,

*/

#[cfg(unix)]
const UNIX_DNS_FILE: &str = "/etc/resolv.conf";

pub fn get_sys_dns() -> Vec<String> {
    #[cfg(unix)]
    {
        let r = std::fs::read_to_string(UNIX_DNS_FILE);
        if let Ok(s) = r {
            return s
                .split('\n')
                .filter(|x| x.starts_with("nameserver"))
                .map(|x| x.split(' ').last().unwrap_or_default().to_string())
                .collect();
        }
    }

    vec![]
}

#[allow(unused)]
pub fn set_sys_dns(list: Vec<&str>) -> std::io::Result<()> {
    #[cfg(target_os = "linux")]
    {
        tracing::debug!("setting system dns");
        let mut s = String::from("# Generated by ruci\n");
        list.iter().for_each(|x| {
            s.push_str("nameserver ");
            s.push_str(x);
            s.push('\n')
        });

        std::fs::write(UNIX_DNS_FILE, s.as_bytes())?;
    }

    Ok(())
}

#[test]
fn test_get() {
    let r = get_sys_dns();
    println!("{r:?}")
}

#[test]
fn test_set() {
    let r = get_sys_dns();
    let r = set_sys_dns(r.iter().map(|x| x.as_str()).collect());
    println!("{r:?}");

    let r = get_sys_dns();

    println!("{r:?}")
}
