fallback_route = [["listen1", "fallback_d"]]

[[inbounds]]
tag = "listen1"

[[inbounds.chain]]

[inbounds.chain.Listener]
listen_addr = "0.0.0.0:10801"

[[inbounds.chain]]

[inbounds.chain.TLS]
cert = "test2.crt"
key = "test2.key"
alpn = ["h2", "http/1.1"]

[[inbounds.chain]]

[inbounds.chain.Trojan]
password = "mypassword"

[[outbounds]]
tag = "dial1"

[[outbounds.chain]]

[outbounds.chain.Direct]
leak_target_addr = true

[[outbounds.chain]]

[outbounds.chain.TLS]
insecure = false
alpn = ["h2", "http/1.1"]

[[outbounds]]
tag = "fallback_d"

[[outbounds.chain]]

[outbounds.chain.BindDialer]
dial_addr = "tcp://0.0.0.0:4433"
