[package]
name = "rucimp"
version = "0.0.2"
edition = "2021"

[dependencies]
ruci = { path = ".." }
bytes = "1"
env_logger = "0.11.1"
log = "0.4.20"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.77" 
futures = "0.3"
futures-lite = "2"
parking_lot = "0.12.1"
dyn-clone = "1"
anyhow = "1"

itertools = "0.12.1"

toml = "0.8.1"
serde = { version = "1", features = ["derive"] }

ipnet = { version = "2.9.0" , optional = true }
iprange = {version = "0.6.7" , optional = true }
regex = {version = "1.10.3" , optional = true }
maxminddb = { version = "0.24", optional = true }

mlua = { version = "0.9.5" , features = ["serialize","async","parking_lot","luau","macros","unstable"] , optional = true }

libc = { version = "0.2", optional = true }

socket2 ={ version = "0.5.6", optional = true } 


macro_mapper ={ path = "../crates/macro_mapper" }

[dependencies.uuid]
version = "1.7.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]


[dev-dependencies]
chrono = "0.4.34"
serde_json = "1.0.114"

[features]
default = ["lua", "route","geoip"]

tun = ["ruci/tun"]
trace = ["ruci/trace"]

lua = ["mlua"]

route = ["ipnet" ,"iprange" ,"regex"]

geoip = ["maxminddb", "route"]

sockopt = ["libc", "socket2"]


[[example]]
name = "chain"
required-features = ["lua", "route"]


