[package]
name = "ruci-cmd"
version = "0.0.0"
edition = "2021"

[dependencies]
ruci = { path = "../.." }
rucimp = { path = "../../rucimp" }
clap = { version = "4.5.1", features = ["derive"] }

axum = {version = "0.7.4", optional = true}

[features]
default = ["api_server"]
api_server = ["axum"]

