[package]
name = "ruci-cmd"
version = "0.0.2"
edition = "2021"

[dependencies]
ruci = { path = "../.." }
rucimp = { path = "../../rucimp" }

tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.10"
futures = "0.3"
tracing = "0.1.40"

tracing-subscriber = { version = "0.3", features = ["env-filter","json"] }
tracing-appender = "=0.2.3"
parking_lot = "0.12.1"

anyhow = "1"
clap = { version = "4.5.1", features = ["derive"] }
bytesize = "1.3.0"


chrono = {version = "0.4.34", optional = true}
axum = {version = "0.7.4", optional = true}
tower = { version = "0.4", features = ["util"] , optional = true}
tower-http = { version = "0.5.0", features = ["fs", "trace","cors"] , optional = true}

TinyUFO = {version = "0.1.0", optional = true }
reqwest = { version = "0.11", features = ["json", "stream"] , optional = true}

[features]
default = ["lua"]
lua = ["rucimp/lua"]
api_server = ["chrono","axum", "tower", "tower-http"]
api_client = ["reqwest"]

utils = ["reqwest"]
trace = ["rucimp/trace","TinyUFO"]

native-tls-vendored = ["rucimp/native-tls-vendored", "reqwest/native-tls-vendored"]