[target.aarch64-unknown-linux-gnu]
image = "openssl:aarch64"
passthrough = [ "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig/"]

[target.aarch64-linux-android]
image = "openssl:android"
passthrough = [ "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-android/pkgconfig/"]
