[book]
authors = ["e1732a364fed"]
language = "zh"
multilingual = false
src = "src"
title = "ruci_manual"

[output.html]
git-repository-url = "https://e1732a364fed.github.io/ruci/"
git-repository-icon = "fa-github"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
