name: Examples

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd rucimp
        cargo build --release --example chain --example suit  --example suit2 --verbose
    - name: Copy Files 
      run: |
        mkdir dist
        cp target/release/examples/chain dist/
        cp target/release/examples/chain.exe dist/
        cp target/release/examples/suit dist/
        cp target/release/examples/suit.exe dist/
        cp target/release/examples/suit2 dist/
        cp target/release/examples/suit2.exe dist/
        cp -r resource dist/

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist
    