name: Examples

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        config:
          - {
              name: "Windows-x86_64", artifact: "Windows-x86_64",
              os: windows-latest,
              has_release: true,
              rust: stable-x86_64-msvc,
              target_triple: x86_64-pc-windows-msvc
            }
          - {
              name: "Linux", artifact: "Linux-x86_64",
              os: ubuntu-latest,
              has_release: true,
              rust: stable,
              target_triple: x86_64-unknown-linux-gnu
            }
          - {
              name: "macOS-x64", artifact: "macOS-x64",
              os: macos-latest,
              rust: stable,
              has_release: true,
              target_triple: x86_64-apple-darwin
            }

    runs-on: ${{ matrix.config.os }}
    name: '${{ matrix.config.name }}'

    steps:
    - uses: actions/checkout@v4
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - run: rustup target add ${{ matrix.config.target_triple }}
    - name: Build
      run: |
        cd rucimp
        cargo build --release --example chain --example suit  --example suit2 --verbose
    - name: Copy Files 
      if: ${{ runner.os != 'Windows' }}
      run: |
        mkdir dist
        cp target/release/examples/chain dist/
        cp target/release/examples/suit dist/ 
        cp target/release/examples/suit2 dist/
        cp -r resource dist/

    - name: Copy Windows Files 
      if: ${{ runner.os == 'Windows' }}
      run: |
        mkdir dist
        cp target/release/examples/chain.exe dist/  
        cp target/release/examples/suit.exe dist/ 
        cp target/release/examples/suit2.exe dist/ 
        cp -r resource dist/
  
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rucimp_${{ steps.get_version.outputs.VERSION }}_${{matrix.config.target_triple}}
        path: |
          dist