name: Ruci-Cmd Release Cross

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:

  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-linux-android
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross #cargo install cross
      
      - name: Build ${{ matrix.target }}
        run: |

          compile_target=${{ matrix.target }}

          cd crates/ruci-cmd
          ./build_cross.sh -v ${{ inputs.tag || github.ref_name }} -t ${{ matrix.target }} -f api_server -f api_client -f utils -f native-tls-vendored -f lua54

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: crates/ruci-cmd/dist/*.tar.xz
          tag_name: ${{ inputs.tag || github.ref_name }}    

