name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
        rustup override set stable
        rustup target add --toolchain stable ${{ matrix.target }}

    - name: Install mingw toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends mingw-w64
    - name: Install ARM compiler toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross aarch64-linux-gnu-g++
    - name: Install ARM7 compiler toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gcc-arm-linux-gnueabihf libc-dev-armhf-cross arm-linux-gnueabihf-g++
    - name: Build ${{ matrix.target }}
      if: ${{ matrix.target != 'x86_64-pc-windows-gnu' }}
      run: |
        cd rucimp
        make BUILD_VERSION=${{ inputs.tag || github.ref_name }} BUILD_TRIPLET=${{ matrix.target }}

    - name: Build ${{ matrix.target }}
      if: ${{ matrix.target == 'x86_64-pc-windows-gnu' }}
      run: |
        cd rucimp
        make exe BUILD_VERSION=${{ inputs.tag || github.ref_name }} BUILD_TRIPLET=${{ matrix.target }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.tar.xz
        tag: ${{ github.ref }}
        file_glob: true

  build-unix:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - name: Install GNU tar
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH
  
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable
          rustup target add --toolchain stable ${{ matrix.target }}

      - name: Build ${{ matrix.target }}
        run: |
          cd rucimp
          make BUILD_VERSION=${{ inputs.tag || github.ref_name }} BUILD_TRIPLET=${{ matrix.target }}
  
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.tar.xz
          tag: ${{ github.ref }}
          file_glob: true