name: Test Features

on:
  workflow_dispatch:
  push:
    branches: [ "tokio" ]
    paths-ignore: 
      - '**.md'
      - '.github/workflows/*.yml'
      - '**/Makefile'
      - '**/Cross.toml'
      
  pull_request:
    branches: [ "tokio" ]
    paths-ignore: 
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  test_features:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - name: Build
      run: cargo build --verbose

    - name: Test Ruci Every feature tag
      run: cargo hack check --feature-powerset --no-dev-deps

    - name: Test Rucimp Every feature tag
      run: cd rucimp && cargo hack check --feature-powerset --no-dev-deps --mutually-exclusive-features lua54,lua --mutually-exclusive-features quic,quinn --mutually-exclusive-features use-native-tls,native-tls-vendored

    - name: Test Ruci-Cmd Every feature tag
      run: cd crates/ruci-cmd && cargo hack check --feature-powerset --no-dev-deps --mutually-exclusive-features lua54,lua --mutually-exclusive-features quic,quinn --mutually-exclusive-features use-native-tls,native-tls-vendored