name: Test Features

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

  pull_request:
    branches: ["tokio"]
    paths-ignore:
      - "**.md"
      - "doc/**"
      - "resource/**"
      - "**/Makefile"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test_features:
    strategy:
      matrix:
        platform:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        crate: [./, rucimp, crates/ruci-cmd]

    runs-on: ${{ matrix.platform }}
    env:
      COMMON_FLAGS: "--no-dev-deps --mutually-exclusive-features lua54,lua --mutually-exclusive-features quic,quinn --mutually-exclusive-features use-native-tls,native-tls-vendored"

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.6.26
      - name: Basic Build
        run: cargo build

      - name: Check  ${{ matrix.crate }} Every feature tag
        run: cd ${{ matrix.crate }} && cargo hack check --clean-per-run --feature-powerset $COMMON_FLAGS

      - name: Test  ${{ matrix.crate }} Every feature tag
        run: cd ${{ matrix.crate }} && cargo hack test --clean-per-run --each-feature $COMMON_FLAGS
