name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "tokio" ]
    paths-ignore: 
      - '**.md'
      - '.github/workflows/*.yml'
      - '**/Makefile'
      - '**/Cross.toml'
      
  pull_request:
    branches: [ "tokio" ]
    paths-ignore: 
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - name: Build
      run: cargo build --verbose

    - name: Run Ruci tests
      run: cargo test --verbose

    - name: Run Rucimp tests
      run: cd rucimp && cargo test --verbose

    - name: Run Ruci-cmd tests
      run: cd crates/ruci-cmd && cargo test --verbose